### ISSUE TITLE
[US] User Story as GitHub issues

### ISSUE THREAD

**Issue by jonathan-ywahashi** [jonathan-ywahashi/study-game-conception2#1]
### User Story

> **As a** product owner,
> **I want to** create backlog items utilizing GitHub's issues,
> **So that** I can use Scrum methodology to facilitate the project development.

### Acceptance Criteria

- Be able to create a ***User Story*** issue template
- Be able to assign Scrum related labels, such as `priority`, `points` and `type`
- Be able to assign the issue to a Sprint through the use of milestones

### Tasks

- [ ] Create a issue template named ***User Story*** with the following topics: `User Story`, `Acceptance Criteria` and `Tasks`
- [ ] Create Scrum related labels: `priority`, `points` and `type`
- [ ] Create a naming convention for milestones (Sprints)

### Additional Notes

This kind of approach in applying Scrum methodology on GitHub comes from [this repository](https://github.com/jvandemo/github-scrum-workflow).
